spring:
  profiles:
    active: development
  application:
    name: springboot-clean-arch-boilterplate
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      auto-commit: true
      minimum-idle: 5
      maximum-pool-size: 20
      transaction-isolation: transaction_read_committed
      connection-timeout: 30000
  jmx:
    enabled: false
  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console


  # 카프카 설정
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
#        spring.json.trusted.packages: com.jindevst.springbootcleanarchboilterplate.model
        spring.json.trusted.packages: com.jindevst.springbootcleanarchboilterplate
    consumer:
      group-id: ticket-reservation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
#        spring.json.trusted.packages: com.jindevst.springbootcleanarchboilterplate.model
        spring.json.trusted.packages: com.jindevst.springbootcleanarchboilterplate

    # 토픽 설정
    topics:
      reservation-request: reservation-requests
      reservation-confirmed: reservation-confirmed
      payment-request: payment-requests
      payment-confirmed: payment-confirmed
      notification: notifications

# 서버 포트 설정
server:
  port: 8080

# 로깅 설정
logging:
  level:
    root: INFO
    com.jindevst.springbootcleanarchboilterplate: DEBUG
    org.springframework.kafka: INFO

# 회복성 설정 (Circuit Breaker)
resilience4j:
  circuitbreaker:
    instances:
      reservationService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50